services:
  dynamic_form.twig.form_element.extention:
    class: 'DynamicFormBundle\Twig\FormElementExtension'
    tags:
      - { name: 'twig.extension' }

  dynamic_form.twig.dynamic_form.extention:
    class: 'DynamicFormBundle\Twig\DynamicFormExtension'
    tags:
      - { name: 'twig.extension' }

  dynamic_form.file_value.listener:
    class: 'DynamicFormBundle\EventListener\Values\FileListener'
    arguments: ['%dynamic_form.file_upload_dir%']
    tags:
      - { name: 'doctrine.orm.entity_listener' }

  dynamic_form.type:
    class: 'DynamicFormBundle\Form\Type\DynamicFormType'
    arguments: ['@dynamic_form.form_type.registry', '@dynamic_form.data_mapper', '@dynamic_form.option_builder']
    tags:
      - { name: 'form.type' }

  dynamic_form.field_value.type:
    class: 'DynamicFormBundle\Form\Type\FieldValueType'
    arguments: ['@dynamic_form.form_type.registry', '@dynamic_form.option_builder']
    tags:
      - { name: 'form.type' }

  dynamic_form.data_mapper:
    class: 'DynamicFormBundle\Services\FormType\DynamicFormDataMapper'
    arguments: ['@dynamic_form.result_field_builder']

  dynamic_form.option_builder:
    class: 'DynamicFormBundle\Services\FormField\OptionBuilder'
    arguments: ['@dynamic_form.option_filter']

  dynamic_form.option_filter:
    class: 'DynamicFormBundle\Services\FormField\OptionFilter'
    arguments: ['%dynamic_form.form_field.disable_options%']

  dynamic_form.result_field_builder:
    class: 'DynamicFormBundle\Services\DynamicResultFieldBuilder'
    arguments: ['@dynamic_form.form_type.registry']

  dynamic_form.form_type.registry:
    class: 'DynamicFormBundle\Services\FormType\Configuration\Registry'
    arguments: ['%dynamic_form.form_field.disable_form_types%']

  dynamic_form.text.type_configuration:
    class: 'DynamicFormBundle\Services\FormType\Configuration\TextTypeConfiguration'
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  dynamic_form.textarea.type_configuration:
    class: 'DynamicFormBundle\Services\FormType\Configuration\TextAreaTypeConfiguration'
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  dynamic_form.checkbox_group.type_configuration:
    class: 'DynamicFormBundle\Services\FormType\Configuration\CheckboxGroupTypeConfiguration'
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  dynamic_form.radio_group.type_configuration:
    class: 'DynamicFormBundle\Services\FormType\Configuration\RadioGroupTypeConfiguration'
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  dynamic_form.select.type_configuration:
    class: 'DynamicFormBundle\Services\FormType\Configuration\SelectTypeConfiguration'
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  dynamic_form.date.type_configuration:
    class: 'DynamicFormBundle\Services\FormType\Configuration\DateTypeConfiguration'
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  dynamic_form.date_time.type_configuration:
    class: 'DynamicFormBundle\Services\FormType\Configuration\DateTimeTypeConfiguration'
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  dynamic_form.file.type_configuration:
    class: 'DynamicFormBundle\Services\FormType\Configuration\FileTypeConfiguration'
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }