services:
  DynamicFormBundle\Admin\Form\Type\DynamicForm\FormFieldType:
    public: true
    arguments:
      - '@DynamicFormBundle\Services\FormType\Configuration\Registry'
      - '@DynamicFormBundle\Admin\Services\FormField\OptionFieldConfigurator'
    tags:
      - { name: 'form.type' }

  DynamicFormBundle\Admin\Services\FormField\OptionFieldBuilder\SingleFieldBuilder:
    public: true
    tags:
      - { name: 'form_field.option_field_builder' }

  DynamicFormBundle\Admin\Services\FormField\OptionFieldBuilder\CollectionFieldBuilder:
    public: true
    tags:
      - { name: 'form_field.option_field_builder' }

  DynamicFormBundle\Admin\Services\FormField\OptionFieldBuilder\ChoiceFieldBuilder:
    public: true
    tags:
      - { name: 'form_field.option_field_builder' }

  DynamicFormBundle\Admin\Services\FormField\OptionFieldConfigurator:
    public: true
    arguments:
      - '@DynamicFormBundle\Admin\Services\FormField\Option\Configuration\Registry'
      - '@DynamicFormBundle\Services\FormField\OptionFilter'

  DynamicFormBundle\Admin\Factory\DynamicForm\FormField\OptionValueFactory:
    public: true
    arguments:
      - '@DynamicFormBundle\Admin\Services\FormField\Option\Configuration\Registry'
      - '@DynamicFormBundle\Admin\Factory\DynamicForm\FormField\ConfigValueFactory'

  DynamicFormBundle\Admin\Factory\DynamicForm\FormFieldFactory:
    public: true
    arguments:
      - '@DynamicFormBundle\Services\FormType\Configuration\Registry'
      - '@DynamicFormBundle\Admin\Factory\DynamicForm\FormField\OptionValueFactory'

  DynamicFormBundle\Admin\Services\FormField\TemplateGuesser:
    public: true
    arguments: ['@twig']

  DynamicFormBundle\Admin\Services\FormField\Option\Configuration\Registry:
    public: true

  DynamicFormBundle\Admin\Services\FormField\Option\Configuration\LabelConfiguration:
    public: true
    tags:
      - { name: 'form_field.option_configuration' }

  DynamicFormBundle\Admin\Services\FormField\Option\Configuration\RequiredConfiguration:
    public: true
    tags:
      - { name: 'form_field.option_configuration' }

  DynamicFormBundle\Admin\Services\FormField\Option\Configuration\DisabledConfiguration:
    public: true
    tags:
      - { name: 'form_field.option_configuration' }

  DynamicFormBundle\Admin\Services\FormField\Option\Configuration\ChoicesConfiguration:
    public: true
    tags:
      - { name: 'form_field.option_configuration' }

  DynamicFormBundle\Admin\Services\FormField\Option\Configuration\DateTime\EmptyDataConfiguration:
    public: true
    tags:
      - { name: 'form_field.option_configuration' }

  DynamicFormBundle\Admin\Services\FormField\Option\Configuration\PlaceholderConfiguration:
    public: true
    tags:
      - { name: 'form_field.option_configuration' }


  DynamicFormBundle\Admin\Form\Type\DynamicForm\FormElementType:
    public: true
    arguments: ['@DynamicFormBundle\Admin\Services\FormElement\Configuration\Registry']
    tags:
      - { name: 'form.type' }

  DynamicFormBundle\Admin\Services\FormElement\TemplateGuesser:
    public: true
    arguments: ['@twig']

  DynamicFormBundle\Admin\Factory\DynamicForm\FormElementFactory:
    public: true
    arguments: ['@DynamicFormBundle\Admin\Services\FormElement\Configuration\Registry']

  DynamicFormBundle\Admin\Services\FormElement\Configuration\Registry:
    public: true

  DynamicFormBundle\Admin\Services\FormElement\Configuration\FormHeadlineConfiguration:
    public: true
    tags:
      - { name: 'form_element.configuration' }

  DynamicFormBundle\Admin\Services\FormElement\Configuration\FormTextConfiguration:
    public: true
    tags:
      - { name: 'form_element.configuration' }

  DynamicFormBundle\Admin\Factory\DynamicForm\FormField\ConfigValueFactory:
    public: true

  DynamicFormBundle\Admin\Factory\DynamicForm\FormField\ConfigValue\ChoiceValueFactory:
    public: true
    tags:
      - { name: 'config_value.factory' }

  DynamicFormBundle\Admin\Services\Actions\FormField\CloneAction:
    public: true
    arguments: ['@doctrine.orm.entity_manager']

  DynamicFormBundle\Admin\Services\Actions\FormField\DeleteAction:
    public: true
    arguments: ['@doctrine.orm.entity_manager']

  DynamicFormBundle\Admin\Services\Actions\FormElement\CloneAction:
    public: true
    arguments: ['@doctrine.orm.entity_manager']

  DynamicFormBundle\Admin\Services\Actions\FormElement\DeleteAction:
    public: true
    arguments: ['@doctrine.orm.entity_manager']
