services:
  dynamic_form.admin.form_field.form_type:
    class: 'DynamicFormBundle\Admin\Form\Type\DynamicForm\FormFieldType'
    arguments: ['@dynamic_form.form_type.registry', '@dynamic_form.admin.form_field.option_field_configurator']
    tags:
      - { name: 'form.type' }

  dynamic_form.admin.form_field.single.option_field_builder:
    class: 'DynamicFormBundle\Admin\Services\FormField\OptionFieldBuilder\SingleFieldBuilder'
    tags:
      - { name: 'form_field.option_field_builder' }

  dynamic_form.admin.form_field.collection.option_field_builder:
    class: 'DynamicFormBundle\Admin\Services\FormField\OptionFieldBuilder\CollectionFieldBuilder'
    tags:
      - { name: 'form_field.option_field_builder' }

  dynamic_form.admin.form_field.choices.option_field_builder:
    class: 'DynamicFormBundle\Admin\Services\FormField\OptionFieldBuilder\ChoiceFieldBuilder'
    tags:
      - { name: 'form_field.option_field_builder' }

  dynamic_form.admin.form_field.option_field_configurator:
    class: 'DynamicFormBundle\Admin\Services\FormField\OptionFieldConfigurator'
    arguments: ['@dynamic_form.admin.form_field.option.registry', '@dynamic_form.option_filter']

  dynamic_form.admin.option_value.factory:
    class: 'DynamicFormBundle\Admin\Factory\DynamicForm\FormField\OptionValueFactory'
    arguments: ['@dynamic_form.admin.form_field.option.registry', '@dynamic_form.config_value.factory']

  dynamic_form.admin.form_field.factory:
    class: 'DynamicFormBundle\Admin\Factory\DynamicForm\FormFieldFactory'
    arguments: ['@dynamic_form.form_type.registry', '@dynamic_form.admin.option_value.factory']

  dynamic_form.admin.form_field.template_guesser:
    class: 'DynamicFormBundle\Admin\Services\FormField\TemplateGuesser'
    arguments: ['@templating']

  dynamic_form.admin.form_field.option.registry:
    class: 'DynamicFormBundle\Admin\Services\FormField\Option\Configuration\Registry'

  dynamic_form.admin.form_field.label.option:
    class: 'DynamicFormBundle\Admin\Services\FormField\Option\Configuration\LabelConfiguration'
    tags:
      - { name: 'form_field.option_configuration' }

  dynamic_form.admin.form_field.required.option:
    class: 'DynamicFormBundle\Admin\Services\FormField\Option\Configuration\RequiredConfiguration'
    tags:
      - { name: 'form_field.option_configuration' }

  dynamic_form.admin.form_field.disabled.option:
    class: 'DynamicFormBundle\Admin\Services\FormField\Option\Configuration\DisabledConfiguration'
    tags:
      - { name: 'form_field.option_configuration' }

  dynamic_form.admin.form_field.choices.option:
    class: 'DynamicFormBundle\Admin\Services\FormField\Option\Configuration\ChoicesConfiguration'
    tags:
      - { name: 'form_field.option_configuration' }

  dynamic_form.admin.form_field.date_time.empty_data.option:
    class: 'DynamicFormBundle\Admin\Services\FormField\Option\Configuration\DateTime\EmptyDataConfiguration'
    tags:
      - { name: 'form_field.option_configuration' }

  dynamic_form.admin.form_field.placeholder.option:
    class: 'DynamicFormBundle\Admin\Services\FormField\Option\Configuration\PlaceholderConfiguration'
    tags:
      - { name: 'form_field.option_configuration' }


  dynamic_form.admin.form_element.type:
    class: 'DynamicFormBundle\Admin\Form\Type\DynamicForm\FormElementType'
    arguments: ['@dynamic_form.admin.form_element.registry']
    tags:
      - { name: 'form.type' }

  dynamic_form.admin.form_element.template_guesser:
    class: 'DynamicFormBundle\Admin\Services\FormElement\TemplateGuesser'
    arguments: ['@templating']

  dynamic_form.admin.form_element.factory:
    class: 'DynamicFormBundle\Admin\Factory\DynamicForm\FormElementFactory'
    arguments: ['@dynamic_form.admin.form_element.registry']

  dynamic_form.admin.form_element.registry:
    class: 'DynamicFormBundle\Admin\Services\FormElement\Configuration\Registry'

  dynamic_form.admin.form_element.headline:
    class: 'DynamicFormBundle\Admin\Services\FormElement\Configuration\FormHeadlineConfiguration'
    tags:
      - { name: 'form_element.configuration' }

  dynamic_form.admin.form_element.text:
    class: 'DynamicFormBundle\Admin\Services\FormElement\Configuration\FormTextConfiguration'
    tags:
      - { name: 'form_element.configuration' }

  dynamic_form.config_value.factory:
    class: 'DynamicFormBundle\Admin\Factory\DynamicForm\FormField\ConfigValueFactory'

  dynamic_form.choice_value.factory:
    class: 'DynamicFormBundle\Admin\Factory\DynamicForm\FormField\ConfigValue\ChoiceValueFactory'
    tags:
      - { name: 'config_value.factory' }

  dynamic_form.admin.action.form_field.clone:
    class: 'DynamicFormBundle\Admin\Services\Actions\FormField\CloneAction'
    arguments: ['@doctrine.orm.entity_manager']

  dynamic_form.admin.action.form_field.delete:
    class: 'DynamicFormBundle\Admin\Services\Actions\FormField\DeleteAction'
    arguments: ['@doctrine.orm.entity_manager']

  dynamic_form.admin.action.form_element.clone:
    class: 'DynamicFormBundle\Admin\Services\Actions\FormElement\CloneAction'
    arguments: ['@doctrine.orm.entity_manager']

  dynamic_form.admin.action.form_element.delete:
    class: 'DynamicFormBundle\Admin\Services\Actions\FormElement\DeleteAction'
    arguments: ['@doctrine.orm.entity_manager']