services:
  DynamicFormBundle\Twig\FormElementExtension:
    public: true
    tags:
      - { name: 'twig.extension' }

  DynamicFormBundle\Twig\DynamicFormExtension:
    public: true
    tags:
      - { name: 'twig.extension' }

  DynamicFormBundle\EventListener\Values\FileListener:
    public: true
    arguments: ['%dynamic_form.file_upload_dir%']
    tags:
      - { name: 'doctrine.orm.entity_listener' }

  DynamicFormBundle\Form\Type\DynamicFormType:
    public: true
    arguments:
      - '@DynamicFormBundle\Services\FormType\Configuration\Registry'
      - '@DynamicFormBundle\Services\FormType\DynamicFormDataMapper'
      - '@DynamicFormBundle\Services\FormField\OptionBuilder'
    tags:
      - { name: 'form.type' }

  DynamicFormBundle\Form\Type\FieldValueType:
    public: true
    arguments:
      - '@DynamicFormBundle\Services\FormType\Configuration\Registry'
      - '@DynamicFormBundle\Services\FormField\OptionBuilder'
    tags:
      - { name: 'form.type' }

  DynamicFormBundle\Services\FormType\DynamicFormDataMapper:
    public: true
    arguments: ['@DynamicFormBundle\Services\DynamicResultFieldBuilder']

  DynamicFormBundle\Services\FormField\OptionBuilder:
    public: true
    arguments: ['@DynamicFormBundle\Services\FormField\OptionFilter']

  DynamicFormBundle\Services\FormField\OptionFilter:
    public: true
    arguments: ['%dynamic_form.form_field.disable_options%']

  DynamicFormBundle\Services\DynamicResultFieldBuilder:
    public: true
    arguments: ['@DynamicFormBundle\Services\FormType\Configuration\Registry']

  DynamicFormBundle\Services\FormType\Configuration\Registry:
    public: true
    arguments: ['%dynamic_form.form_field.disable_form_types%']

  DynamicFormBundle\Services\FormType\Configuration\TextTypeConfiguration:
    public: true
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  DynamicFormBundle\Services\FormType\Configuration\TextAreaTypeConfiguration:
    public: true
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  DynamicFormBundle\Services\FormType\Configuration\CheckboxGroupTypeConfiguration:
    public: true
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  DynamicFormBundle\Services\FormType\Configuration\RadioGroupTypeConfiguration:
    public: true
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  DynamicFormBundle\Services\FormType\Configuration\SelectTypeConfiguration:
    public: true
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  DynamicFormBundle\Services\FormType\Configuration\DateTypeConfiguration:
    public: true
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  DynamicFormBundle\Services\FormType\Configuration\DateTimeTypeConfiguration:
    public: true
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }

  DynamicFormBundle\Services\FormType\Configuration\FileTypeConfiguration:
    public: true
    arguments: ['%dynamic_form.form_field.global_options%']
    tags:
      - { name: 'form.type_configuration' }
