language: php
sudo: false
branches:
  except:
    - experimental
cache:
  directories:
    - $HOME/.composer/cache/files
matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
  fast_finish: true
before_install:
  - composer selfupdate
script:
  - composer install --no-interaction
  - ./bin/phpcs.phar --standard=PSR2 ./src -v
  - ./bin/phpcpd.phar ./src
  - ./bin/phpunit.phar --coverage-clover build/logs/clover.xml