language: php
sudo: false
branches:
  except:
    - experimental
cache:
  directories:
    - $HOME/.composer/cache/files
matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
  fast_finish: true
before_install:
  - composer selfupdate
script:
  - composer update --no-interaction
  - ./bin/phpcs.phar --ignore=./vendor/,./Tests/Fixtures/,./bin --standard=PSR2 ./ -v
  - ./bin/phpcpd.phar --exclude=vendor --exclude=Tests/Fixtures --exclude=bin  ./
  - ./bin/phpunit.phar --coverage-clover build/logs/clover.xml